name: The NPM package uploading

on:
  push:
    tags:
      - '*'

jobs:
  sdk-nodejs-release:
    name: "Release NodeJS SDK"
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/feature/pulumi-component'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go âœ¨
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: pulumi-component/provider/go.mod
      - name: Wait for tests on main
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: main
          running-workflow-name: "The cluster deployment for examples for long-living branches"
          repo-token: ${{ github.token }}
          wait-interval: 10
      - name: Wait unit for tests on main
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: main
          running-workflow-name: "Run tests and linter for all branches"
          repo-token: ${{ github.token }}
          wait-interval: 10
      - name: Generate nodejs sdk package
        run: make build_nodejs_sdk
        working-directory: pulumi-component
      - name: Publish package to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          package: pulumi-component/sdk/nodejs/bin
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
